name: Build and Commit Cython Extensions

on:
  push:
    paths:
      - 'retopoflow/cy/*.pyx'
      - 'retopoflow/cy/*.pxd'
      - 'cy_setup.py'
      - '.github/workflows/build_cython.yml'
    branches:
      - v3-performance # Or specific branches where commits should happen
  pull_request:
    paths:
      - 'retopoflow/cy/*.pyx'
      - 'retopoflow/cy/*.pxd'
      - 'cy_setup.py'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build B${{ matrix.config.blender }} on ${{ matrix.config.os }} (${{ matrix.config.target || 'default' }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        # Define the 8 core build configurations explicitly
        config:
          # Linux
          - { os: ubuntu-latest, blender: '4.3', target: default, compile_target: default }
          - { os: ubuntu-latest, blender: '4.4', target: default, compile_target: default }
          # Windows
          - { os: windows-latest, blender: '4.3', target: default, compile_target: default }
          - { os: windows-latest, blender: '4.4', target: default, compile_target: default }
          # macOS Arm64
          - { os: macos-latest, blender: '4.3', target: native, compile_target: arm64 }
          - { os: macos-latest, blender: '4.4', target: native, compile_target: arm64 }
          # macOS x86_64
          - { os: macos-latest, blender: '4.3', target: intel, compile_target: x86_64 }
          - { os: macos-latest, blender: '4.4', target: intel, compile_target: x86_64 }
        python-version: ['3.11'] # Common factor, keep here

    env:
      # Define Blender version specific dependencies here
      NUMPY_VERSION_4_3: '1.24.4'
      OUTPUT_SUFFIX_4_3: '43'
      NUMPY_VERSION_4_4: '1.26.4'
      OUTPUT_SUFFIX_4_4: '44'
      # Common Cython version
      CYTHON_VERSION: '3.0.11'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Version Specific Vars based on Blender Version
      id: vars
      shell: bash
      run: |
        bl_ver="${{ matrix.config.blender }}"
        if [[ "$bl_ver" == "4.3" ]]; then
          echo "NUMPY_VERSION=${{ env.NUMPY_VERSION_4_3 }}" >> $GITHUB_OUTPUT
          echo "OUTPUT_SUFFIX=${{ env.OUTPUT_SUFFIX_4_3 }}" >> $GITHUB_OUTPUT
        elif [[ "$bl_ver" == "4.4" ]]; then
          echo "NUMPY_VERSION=${{ env.NUMPY_VERSION_4_4 }}" >> $GITHUB_OUTPUT
          echo "OUTPUT_SUFFIX=${{ env.OUTPUT_SUFFIX_4_4 }}" >> $GITHUB_OUTPUT
        else
          echo "Error: Unknown Blender version $bl_ver"
          exit 1
        fi
        echo "CYTHON_VERSION=${{ env.CYTHON_VERSION }}" >> $GITHUB_OUTPUT # Output common Cython version too

    - name: Set up MSVC (Visual Studio 2022)
      if: matrix.config.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Debug build environment info
      shell: bash
      run: |
        echo "Python Version: $(python --version)"
        echo "Platform: $(python -c 'import platform; print(platform.platform())')"
        echo "Machine: $(python -c 'import platform; print(platform.machine())')"
        echo "OS Env PLAT_NAME: ${{ env.PLAT_NAME || 'N/A' }}"
        echo "Compile Target: ${{ matrix.config.compile_target || 'N/A' }}"
        echo "Blender Version: ${{ matrix.config.blender }}"
        echo "Numpy Version: ${{ steps.vars.outputs.NUMPY_VERSION }}"
        echo "Cython Version: ${{ steps.vars.outputs.CYTHON_VERSION }}"
        echo "Output Suffix: b${{ steps.vars.outputs.OUTPUT_SUFFIX }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==${{ steps.vars.outputs.NUMPY_VERSION }} cython==${{ steps.vars.outputs.CYTHON_VERSION }} setuptools wheel

    # --- Build Commands --- Use cy_setup.py directly
    - name: Build Cython extensions (Windows)
      if: matrix.config.os == 'windows-latest'
      shell: cmd
      run: |
        echo "Building B${{ matrix.config.blender }} for Windows..."
        python cy_setup.py build_ext --inplace --force --blender-version ${{ matrix.config.blender }}
        if %errorlevel% neq 0 exit /b %errorlevel%

    - name: Build Cython extensions (macOS)
      if: matrix.config.os == 'macos-latest'
      shell: bash
      env:
        TARGET_ARCH: ${{ matrix.config.compile_target }}
        ARCHFLAGS: "-arch ${{ matrix.config.compile_target }}"
      run: |
        set -e
        echo "Building B${{ matrix.config.blender }} for macOS with arch: $TARGET_ARCH..."
        python cy_setup.py build_ext --inplace --force --blender-version ${{ matrix.config.blender }}

    - name: Build Cython extensions (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      shell: bash
      run: |
        set -e
        echo "Building B${{ matrix.config.blender }} for Linux..."
        python cy_setup.py build_ext --inplace --force --blender-version ${{ matrix.config.blender }}

    - name: List compiled files in output dir
      shell: bash
      run: |
        echo "Checking for compiled files in retopoflow/compiled/b${{ steps.vars.outputs.OUTPUT_SUFFIX }} ..."
        ls -lR retopoflow/compiled/b${{ steps.vars.outputs.OUTPUT_SUFFIX }} || echo "Directory not found or empty."
        echo "Searching for .so/.pyd files..."
        find retopoflow/compiled/b${{ steps.vars.outputs.OUTPUT_SUFFIX }} -type f \( -name "*.so" -o -name "*.pyd" \) -print
        if ! find retopoflow/compiled/b${{ steps.vars.outputs.OUTPUT_SUFFIX }} -type f \( -name "*.so" -o -name "*.pyd" \) | grep -q .; then
          echo "Warning: No compiled extensions found in expected output directory!"
        fi

    - name: Upload compiled version directory
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: compiled-b${{ steps.vars.outputs.OUTPUT_SUFFIX }}-${{ matrix.config.os }}-${{ matrix.config.target || 'default' }}
        path: retopoflow/compiled/b${{ steps.vars.outputs.OUTPUT_SUFFIX }}
        if-no-files-found: warn
        retention-days: 7

  commit-compiled-files:
    needs: build
    runs-on: ubuntu-latest
    # Only run this job on pushes to the specified branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/v3-performance'
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        # Need fetch-depth 0 for git push
        fetch-depth: 0

    - name: Download all compiled artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts # Download all artifacts into 'artifacts/' directory

    - name: List downloaded artifacts
      run: ls -lR artifacts

    - name: Merge compiled artifacts into retopoflow/compiled
      shell: bash
      run: |
        set -e # Exit immediately if a command exits with a non-zero status.

        echo "Creating final retopoflow/compiled directory..."
        # Remove existing compiled dir first to ensure clean state, handle case where it doesn't exist
        rm -rf retopoflow/compiled || true
        mkdir -p retopoflow/compiled

        echo "Merging artifact contents directly into retopoflow/compiled/bXX/ ..."

        # Iterate through each downloaded artifact directory (e.g., artifacts/compiled-b43-...)
        find artifacts -mindepth 1 -maxdepth 1 -type d -name 'compiled-b*' -print0 | while IFS= read -r -d $'\0' artifact_dir; do
            artifact_name=$(basename "$artifact_dir")
            echo "============================================"
            echo " Processing artifact dir: $artifact_name"

            # Extract the bXX version (e.g., b43, b44) from the artifact directory name
            if [[ "$artifact_name" =~ compiled-(b[0-9]+)- ]]; then
                version_dir_name="${BASH_REMATCH[1]}" # Extracts 'b43' or 'b44'
                echo "  Detected version: $version_dir_name"
            else
                echo "  Warning: Could not determine bXX version from artifact name '$artifact_name'. Skipping."
                echo "============================================"
                continue
            fi

            # Define the source directory (the root of the artifact)
            source_dir="$artifact_dir"
            # Construct the target directory path in the workspace
            target_compiled_dir="retopoflow/compiled/$version_dir_name"

            echo "  Source dir (artifact root): $source_dir"
            echo "  Target dir: $target_compiled_dir"

            # Ensure the target version directory exists within retopoflow/compiled
            mkdir -p "$target_compiled_dir"

            # List contents of the artifact directory before copy
            echo "  Source contents in $source_dir:"
            ls -lA "$source_dir" || echo "  Warning: Could not list source directory $source_dir"

            # Copy the *contents* of the artifact directory into the target bXX directory
            # Use 'cp -a SOURCE/. TARGET/' pattern to merge contents
            echo "  Executing copy command: cp -a '$source_dir/.' '$target_compiled_dir/'"
            cp -a "$source_dir/." "$target_compiled_dir/" || echo "  ERROR: Copy command failed for '$source_dir'"
            echo "  Copy finished for $source_dir."
            echo "============================================"

        done
        echo "Finished merging loop."

    - name: Verify final compiled structure
      run: |
        echo "Final compiled directory structure after merge:"
        ls -lR retopoflow/compiled || echo "Warning: retopoflow/compiled directory not found or empty after merge attempt."
        echo "Checking for expected binaries:"
        find retopoflow/compiled -type f \( -name "*.so" -o -name "*.pyd" \) -print || echo "Warning: No .so or .pyd files found."

    - name: Configure Git and .gitattributes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit and push changes
      run: |
        echo "Staging compiled files..."
        git add retopoflow/compiled

        echo "Checking for staged changes..."
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes detected in compiled files or .gitattributes to commit."
        else
          echo "Changes detected. Committing..."
          git commit -m "Update compiled Cython extensions [skip ci]"
          echo "Pushing changes..."
          git push
        fi